---

- hosts: jukebox
  gather_facts: Yes

  tasks:
    - name: include os tasks
      include: includes/debian.yml
      tags:
        - os
    - name: include lvm tasks
      include: includes/lvm.yml
      tags:
        - lvm
    - name: include unattended-upgrades tasks
      include: includes/unattended-upgrades.yml
      tags:
        - unattended
    - name: include samba tasks
      include: includes/samba.yml
      tags:
        - samba
    - name: include rtc tasks
      include: includes/rtc.yml
      tags:
        - rtc

  handlers:
    - name: restart samba
      become: yes
      service:
        name: smbd
        state: restarted
    - name: restart apt-daily.timer
      systemd:
        state: restarted
        daemon_reload: yes
        name: apt-daily.timer
    - name: restart service apt-daily-upgrade.timer
      systemd:
        state: restarted
        daemon_reload: yes
        name: apt-daily-upgrade.timer