---

# rtcwake and cron job configuration:
#   name: cron job name
#   hour: time (hour) execution cron job
#   minute: time (minute) execution cron job
#   weekday: days when the cron job is executed
#   sleeptime: how much time (s) rtcwake must sleep
#   state: present (default) or absent, create or delete the cron job
rtcwake:
  # extinction de 01:00 à 06:00 LMMJV
  - name: "Night stop"
    hour: "01"
    minute: "00"
    weekday: "3-5"
    sleep_time: 18000
    state: present
  # extinction de 01:00 à 06:00 MJV
  - name: "Short Night stop"
    hour: "01"
    minute: "00"
    weekday: "3-5"
    sleep_time: 18000
    state: absent
  # extinction de 01:00 à 17:00 LM
  - name: "Long Night stop"
    hour: "01"
    minute: "00"
    weekday: "1-2"
    sleep_time: 57600
    state: absent
  # extinction de 10:00 à 18:00 LMMJV / short stop
  - name: "Morning stop"
    hour: "10"
    minute: "00"
    weekday: "3-5"
    sleep_time: 28800
    state: absent
  # extinction de 02:30 à 08:00 SD
  - name: "Weekend stop"
    hour: "02"
    minute: "30"
    weekday: "6-7"
    sleep_time: 19800
    state: present
