---

rtcwake:
  # extinction de 01:00 à 01:55 LMMJVSD
  - name: "Night stop"
    minute: "00"
    hour: "01"
    weekday: "1-7"
    sleep_time: 3300
  # extinction de 02:30 à 03:55 LMMJV
  - name: "Music Library Update stop"
    minute: "30"
    hour: "02"
    weekday: "1-5"
    sleep_time: 5100
    # extinction de 05:00 à 06:00 LMMJV
  - name: "Server Update stop"
    minute: "00"
    hour: "05"
    weekday: "1-5"
    sleep_time: 3600
  # extinction de 08:30 à 18:00 LMMJV
  - name: "Morning stop"
    minute: "30"
    hour: "08"
    weekday: "1-5"
    sleep_time: 32430
  # extinction de 02:30 à 08:00 SD
  - name: "Weekend stop"
    minute: "30"
    hour: "02"
    weekday: "6-7"
    sleep_time: 19800